#!/usr/bin/env bun
/**
 * DevOps and infrastructure CLI queries
 */

export const DEVOPS_QUERIES = [
  "CLI tool",
  "command line tool",
  "devops CLI",
  "developer CLI",
  "productivity CLI",
  "automation CLI",
  "monitoring CLI",
  "API CLI",
  "cloud CLI",
  "database CLI",
  "testing CLI",
  "build tool CLI",
  "deployment CLI",
  "docker CLI",
  "kubernetes CLI",
  "git CLI",
  "AWS CLI",
  "security CLI",
  "network CLI",
  "backup CLI",
  "system monitoring CLI",
  "process management CLI",
  "container CLI",
  "virtualization CLI",
  "storage CLI",
  "CDN CLI",
  "DNS CLI",
  "proxy CLI",
  "firewall CLI",
  "VPN CLI",
  "SSH CLI",
  "SSL/TLS CLI",
  "certificate CLI",
  "key management CLI",
  "secret management CLI",
  "configuration CLI",
  "template CLI",
  "generator CLI",
  "scaffolding CLI",
  "boilerplate CLI",
  "migration CLI",
  "sync CLI",
  "backup CLI",
  "restore CLI",
  "archive CLI",
  "compression CLI",
  "encryption CLI",
  "decryption CLI",
  "hash CLI",
  "encoding CLI",
  "decoding CLI",
  "format conversion CLI",
  "file transfer CLI",
  "upload CLI",
  "download CLI",
  "streaming CLI",
  "batch processing CLI",
  "job scheduling CLI",
  "task runner CLI",
  "workflow CLI",
  "pipeline CLI",
  "orchestration CLI",
  "service mesh CLI",
  "API gateway CLI",
  "load balancer CLI",
  "reverse proxy CLI",
  "web server CLI",
  "application server CLI",
  "database migration CLI",
  "database backup CLI",
  "database restore CLI",
  "database seeding CLI",
  "cache CLI",
  "search CLI",
  "indexing CLI",
  "full-text search CLI",
  "document database CLI",
  "graph database CLI",
  "time series CLI",
  "message queue CLI",
  "event streaming CLI",
  "pub/sub CLI",
  "notification CLI",
  "CI/CD CLI",
  "continuous integration CLI",
  "continuous deployment CLI",
  "release CLI",
  "version CLI",
  "changelog CLI",
  "container CLI",
  "pod CLI",
  "deployment CLI",
  "release CLI",
  "version CLI",
  "update CLI",
  "upgrade CLI",
  "patch CLI",
  "hotfix CLI",
  "rollback CLI",
  "revert CLI",
  "undo CLI",
  "redo CLI",
  "branch CLI",
  "merge CLI",
  "rebase CLI",
  "cherry-pick CLI",
  "stash CLI",
  "tag CLI",
  "commit CLI",
  "push CLI",
  "pull CLI",
  "fetch CLI",
  "clone CLI",
  "fork CLI",
  "PR CLI",
  "issue CLI",
  "review CLI",
  "approve CLI",
  "merge CLI",
  "deploy CLI",
  "release CLI",
  "publish CLI",
  "distribute CLI",
  "package CLI",
  "bundle CLI",
  "build CLI",
  "compile CLI",
  "transpile CLI",
  "minify CLI",
  "optimize CLI",
  "compress CLI",
  "obfuscate CLI",
  "encrypt CLI",
  "sign CLI",
  "verify CLI",
  "validate CLI",
  "test CLI",
  "lint CLI",
  "format CLI",
  "document CLI",
  "publish CLI",
  "release CLI",
  "distribute CLI",
  "monitor CLI",
  "analyze CLI",
  "debug CLI",
  "profile CLI",
  "optimize CLI",
  "scale CLI",
  "load balance CLI",
  "cache CLI",
  "CDN CLI",
  "edge CLI",
  "proxy CLI",
  "gateway CLI",
  "firewall CLI",
  "VPN CLI",
  "DNS CLI",
  "SSL CLI",
  "TLS CLI",
  "certificate CLI",
  "key CLI",
  "secret CLI",
  "config CLI",
  "env CLI",
  "variable CLI",
  "parameter CLI",
  "argument CLI",
  "flag CLI",
  "option CLI",
  "setting CLI",
  "preference CLI",
  "profile CLI",
  "account CLI",
  "user CLI",
  "auth CLI",
  "login CLI",
  "logout CLI",
  "register CLI",
  "signup CLI",
  "password CLI",
  "reset CLI",
  "recover CLI",
  "2FA CLI",
  "MFA CLI",
  "OTP CLI",
  "token CLI",
  "session CLI",
  "cookie CLI",
  "cache CLI",
  "storage CLI",
  "database CLI",
  "file CLI",
  "directory CLI",
  "folder CLI",
  "path CLI",
  "URL CLI",
  "URI CLI",
  "link CLI",
  "reference CLI",
  "pointer CLI",
  "handle CLI",
  "ID CLI",
  "UUID CLI",
  "GUID CLI",
  "hash CLI",
  "checksum CLI",
  "signature CLI",
  "fingerprint CLI",
  "timestamp CLI",
  "date CLI",
  "time CLI",
  "timezone CLI",
  "locale CLI",
  "language CLI",
  "encoding CLI",
  "charset CLI",
  "format CLI",
  "parse CLI",
  "serialize CLI",
  "deserialize CLI",
  "encode CLI",
  "decode CLI",
  "compress CLI",
  "decompress CLI",
  "encrypt CLI",
  "decrypt CLI",
  "hash CLI",
  "verify CLI",
  "sign CLI",
  "validate CLI",
  "sanitize CLI",
  "escape CLI",
  "unescape CLI",
  "trim CLI",
  "strip CLI",
  "clean CLI",
  "filter CLI",
  "transform CLI",
  "map CLI",
  "reduce CLI",
  "fold CLI",
  "scan CLI",
  "search CLI",
  "find CLI",
  "locate CLI",
  "grep CLI",
  "match CLI",
  "replace CLI",
  "substitute CLI",
  "split CLI",
  "join CLI",
  "concat CLI",
  "append CLI",
  "prepend CLI",
  "insert CLI",
  "delete CLI",
  "remove CLI",
  "erase CLI",
  "clear CLI",
  "reset CLI",
  "undo CLI",
  "redo CLI",
  "revert CLI",
  "rollback CLI",
  "restore CLI",
  "recover CLI",
  "backup CLI",
  "archive CLI",
  "compress CLI",
  "zip CLI",
  "tar CLI",
  "gzip CLI",
  "bzip2 CLI",
  "xz CLI",
  "7z CLI",
  "rar CLI",
  "extract CLI",
  "unzip CLI",
  "untar CLI",
  "gunzip CLI",
  "bunzip2 CLI",
  "unxz CLI",
  "un7z CLI",
  "unrar CLI"
];
